version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env.${ENV}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: rohit7669/testapp-backend:latest
    container_name: backend
    env_file:
      - .env.${ENV}
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: rohit7669/testapp-frontend:latest
    container_name: frontend
    env_file:
      - .env.${ENV}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: