version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_${ENV}
    env_file:
      - .env.${ENV}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_${ENV}:/var/lib/mysql

  backend:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    image: rohit7669/testapp-backend:latest
    container_name: backend_${ENV}
    env_file:
      - .env.${ENV}
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    image: rohit7669/testapp-frontend:latest
    container_name: frontend_${ENV}
    env_file:
      - .env.${ENV}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data_dev:
  mysql_data_qa:
  mysql_data_prod: