apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-backend
  template:
    metadata:
      labels:
        app: testapp-backend
    spec:
      containers:
        - name: backend
          image: rohit7669/testapp-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/testdb_dev?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: testuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: testpassword
            - name: BACKEND_URL
              value: "http://52.66.205.79:30081/api"